# Generated by Django 5.2.17 on 2026-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(default='ors', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'geocode_cache',
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('retail_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocode_source', models.CharField(default='gazetteer', max_length=20)),
            ],
            options={
                'db_table': 'fuel_stop',
                'indexes': [models.Index(fields=['latitude'], name='fuel_stop_latitud_e6da6a_idx'), models.Index(fields=['longitude'], name='fuel_stop_longitu_a98e95_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('finish_lat', models.FloatField()),
                ('finish_lng', models.FloatField()),
                ('geometry', models.JSONField()),
                ('distance_miles', models.FloatField()),
                ('start_text', models.CharField(blank=True, max_length=255)),
                ('finish_text', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'route_cache',
                'unique_together': {('start_lat', 'start_lng', 'finish_lat', 'finish_lng')},
            },
        ),
    ]
