# Generated by Django 6.1.1 on 2026-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelstop',
            name='fuel_stop_latitud_e6da6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='fuelstop',
            name='fuel_stop_longitu_a98e95_idx',
        ),
        migrations.AddIndex(
            model_name='fuelstop',
            index=models.Index(fields=['latitude', 'longitude'], name='fuel_stop_latitud_2dfc0a_idx'),
        ),
    ]
